# Auto-generated by recall release workflow. Do not edit by hand.
class Recall < Formula
  desc "Local search engine for your notes and documents (BM25 + vector + hybrid fusion)"
  homepage "https://github.com/ugurcan-aytar/recall"
  version "0.1.0"
  license "MIT"

  on_macos do
    # darwin_amd64 (Intel Mac) build is not yet shipped — the
    # macos-13 runner isn't available on the release workflow's
    # account. M-series users are covered.
    on_arm do
      url "https://github.com/ugurcan-aytar/recall/releases/download/v0.1.0/recall_0.1.0_darwin_arm64.tar.gz"
      sha256 "8fa424b25320416370f8e0c599ba9675e9db3dd5ecce985ad19263c4e7f36dbd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ugurcan-aytar/recall/releases/download/v0.1.0/recall_0.1.0_linux_amd64.tar.gz"
      sha256 "72a787aef3bfbef9f227714cc00509b57fafdc02d09c03af8f50076553356dae"
    end
  end

  def install
    bin.install "recall"
  end

  def caveats
    <<~EOS
      recall is installed without the local GGUF embedding backend
      (~146 MB model). To enable vector / hybrid search, either:
        * rebuild from source with -tags 'sqlite_fts5 embed_llama'
          (requires libbinding.a — see github.com/ugurcan-aytar/recall),
        * or set RECALL_EMBED_PROVIDER=openai|voyage and an API key.

      BM25 full-text search via 'recall search' works out of the box.
    EOS
  end

  test do
    system "#{bin}/recall", "version"
  end
end
