# Auto-generated by recall release workflow. Do not edit by hand.
class Recall < Formula
  desc "Local search engine for your notes and documents (BM25 + vector + hybrid fusion)"
  homepage "https://github.com/ugurcan-aytar/recall"
  version "0.2.2"
  license "MIT"

  on_macos do
    # darwin_amd64 (Intel Mac) build is not yet shipped — the
    # macos-13 runner isn't available on the release workflow's
    # account. M-series users are covered.
    on_arm do
      url "https://github.com/ugurcan-aytar/recall/releases/download/v0.2.2/recall_0.2.2_darwin_arm64.tar.gz"
      sha256 "fe274587697147d0eeaeed602ae8260ec12bcaa917c7af170dbf483ab3b282a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ugurcan-aytar/recall/releases/download/v0.2.2/recall_0.2.2_linux_amd64.tar.gz"
      sha256 "23a57dfc0b110f99b6ca596f277741bd267ad0ee1027b253e27f479d300b5666"
    end
  end

  def install
    bin.install "recall"
    # Cobra emits shell completions on demand; this helper
    # picks the right per-shell directory under Homebrew's
    # fpath so users get tab-completion without any
    # post-install setup.
    generate_completions_from_executable(bin/"recall", "completion")
  end

  def caveats
    <<~EOS
      Local GGUF embedding ships baked in. The first time you run
      'recall embed' (or 'recall query --expand|--rerank|--hyde'),
      recall downloads the platform llama.cpp shared library
      (~100 MB, one-time) into ~/.cache/gollama/libs/. Afterwards
      everything runs offline.

      For the embedding model itself:
        recall models download              # nomic-embed-text-v1.5 (~146 MB)
        recall models download --expansion  # qmd-query-expansion-1.7B (~1.3 GB)
        recall models download --reranker   # Qwen2.5-1.5B-Instruct (~1.1 GB)

      Or skip the local model entirely with an API embedder:
        export RECALL_EMBED_PROVIDER=openai|voyage
        export OPENAI_API_KEY=...   # or VOYAGE_API_KEY
    EOS
  end

  test do
    system "#{bin}/recall", "version"
  end
end
